"""Adding Icon Workflow

Revision ID: 1c6f3375819c
Revises: bc8520130736
Create Date: 2025-11-21 12:15:35.302215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c6f3375819c'
down_revision: Union[str, Sequence[str], None] = 'bc8520130736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process_recording_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('icon_value', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('icon_color', sa.String(length=7), nullable=True))

 
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
  
    with op.batch_alter_table('process_recording_sessions', schema=None) as batch_op:
        batch_op.drop_column('icon_color')
        batch_op.drop_column('icon_value')
        batch_op.drop_column('icon_type')

    # ### end Alembic commands ###
