"""Refactor to seperate Folder model

Revision ID: 31636a3debb1
Revises: 3d76bcfc365a
Create Date: 2025-11-15 05:20:18.497099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31636a3debb1'
down_revision: Union[str, Sequence[str], None] = '3d76bcfc365a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folders',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(length=16), nullable=False),
    sa.Column('parent_id', sa.String(length=16), nullable=True),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_expanded', sa.Boolean(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_folders_depth'), ['depth'], unique=False)
        batch_op.create_index(batch_op.f('ix_folders_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_folders_path'), ['path'], unique=False)
        batch_op.create_index(batch_op.f('ix_folders_position'), ['position'], unique=False)
        batch_op.create_index(batch_op.f('ix_folders_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder_id', sa.String(length=16), nullable=True))
        batch_op.drop_index(batch_op.f('ix_documents_depth'))
        batch_op.drop_index(batch_op.f('ix_documents_parent_id'))
        batch_op.drop_index(batch_op.f('ix_documents_path'))
        batch_op.drop_index(batch_op.f('ix_documents_position'))
        batch_op.create_index(batch_op.f('ix_documents_folder_id'), ['folder_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('documents_parent_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'folders', ['folder_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('icon')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('depth')
        batch_op.drop_column('path')
        batch_op.drop_column('is_expanded')
        batch_op.drop_column('position')
        batch_op.drop_column('app_config')
        batch_op.drop_column('doc_type')

  




def downgrade() -> None:
    """Downgrade schema."""


    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doc_type', sa.VARCHAR(length=11), server_default=sa.text("'document'::character varying"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('app_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_expanded', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('path', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('depth', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('parent_id', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('icon', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('documents_parent_id_fkey'), 'documents', ['parent_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_documents_folder_id'))
        batch_op.create_index(batch_op.f('ix_documents_position'), ['position'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_path'), ['path'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_depth'), ['depth'], unique=False)
        batch_op.drop_column('folder_id')

    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_folders_project_id'))
        batch_op.drop_index(batch_op.f('ix_folders_position'))
        batch_op.drop_index(batch_op.f('ix_folders_path'))
        batch_op.drop_index(batch_op.f('ix_folders_parent_id'))
        batch_op.drop_index(batch_op.f('ix_folders_depth'))

    op.drop_table('folders')
    # ### end Alembic commands ###
