"""Intial migration

Revision ID: 3d76bcfc365a
Revises: 
Create Date: 2025-11-14 18:36:31.724447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d76bcfc365a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_container',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('content', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('normalized_email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_tok', sa.String(length=32), nullable=True),
    sa.Column('reset_token', sa.String(length=32), nullable=True),
    sa.Column('reset_expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_normalized_email'), ['normalized_email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_reset_token'), ['reset_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_verification_tok'), ['verification_tok'], unique=False)

    op.create_table('auth_codes',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=16), nullable=False),
    sa.Column('code_challenge', sa.String(length=128), nullable=False),
    sa.Column('code_challenge_method', sa.String(length=10), nullable=False),
    sa.Column('redirect_uri', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('code')
    )
    with op.batch_alter_table('auth_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_codes_user_id'), ['user_id'], unique=False)

    op.create_table('process_recording_sessions',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.String(length=16), nullable=True),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('total_files', sa.Integer(), nullable=True),
    sa.Column('steps_metadata', sa.JSON(), nullable=True),
    sa.Column('storage_type', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('process_recording_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_process_recording_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=True),
    sa.Column('owner_id', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_name'), ['name'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('dashboards',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.String(length=16), nullable=False),
    sa.Column('layout', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dashboards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dashboards_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dashboards_user_id'), ['user_id'], unique=False)

    op.create_table('process_recording_files',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('session_id', sa.String(length=16), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['process_recording_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'step_number', name='_session_step_unique')
    )
    with op.batch_alter_table('process_recording_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_process_recording_files_session_id'), ['session_id'], unique=False)

    op.create_table('project_members',
    sa.Column('user_id', sa.String(length=16), nullable=False),
    sa.Column('project_id', sa.String(length=16), nullable=False),
    sa.Column('role', sa.Enum('viewer', 'member', 'editor', 'admin', 'owner', name='project_role_enum', native_enum=False), server_default=sa.text("'member'"), nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('invited_by', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'project_id'),
    sa.UniqueConstraint('user_id', 'project_id', name='_project_member_unique')
    )
    op.create_table('table_meta',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('physical_name', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(length=16), nullable=True),
    sa.Column('table_type', sa.Enum('user', 'join', 'other', name='table_type_enum', native_enum=False, create_constraint=True), server_default=sa.text("'user'"), nullable=False),
    sa.Column('has_order_column', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('physical_name')
    )
    with op.batch_alter_table('table_meta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_table_meta_name'), ['name'], unique=False)

    op.create_table('column_meta',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('table_id', sa.String(length=16), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ui_type', sa.String(), nullable=True),
    sa.Column('fk_type', sa.String(), nullable=True),
    sa.Column('relations_table_id', sa.String(length=16), nullable=True),
    sa.Column('column_type', sa.Enum('physical', 'virtual', name='column_type_enum', native_enum=False, create_constraint=True), server_default=sa.text("'physical'"), nullable=False),
    sa.Column('sr__order', sa.Integer(), server_default=sa.text('1000'), nullable=False),
    sa.Column('default_value', sa.JSON(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['table_meta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dashboard_widgets',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('dashboard_id', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('chart_type', sa.String(), nullable=False),
    sa.Column('table_id', sa.String(length=16), nullable=False),
    sa.Column('x_axis_column', sa.String(), nullable=True),
    sa.Column('y_axis_column', sa.String(), nullable=True),
    sa.Column('group_by_column', sa.String(), nullable=True),
    sa.Column('aggregation', sa.String(), nullable=True),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('w', sa.Integer(), nullable=False),
    sa.Column('h', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['table_meta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dashboard_widgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dashboard_widgets_dashboard_id'), ['dashboard_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('content', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('page_layout', sa.String(length=20), server_default='full', nullable=False),
    sa.Column('doc_type', sa.Enum('document', 'application', 'app_page', 'folder', 'workflow', name='document_type_enum', native_enum=False, create_constraint=True), server_default=sa.text("'document'"), nullable=False),
    sa.Column('app_config', sa.JSON(), nullable=True),
    sa.Column('project_id', sa.String(length=16), nullable=False),
    sa.Column('linked_table_id', sa.String(length=16), nullable=True),
    sa.Column('linked_row_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.String(length=16), nullable=True),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_expanded', sa.Boolean(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['linked_table_id'], ['table_meta.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_depth'), ['depth'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_linked_row_id'), ['linked_row_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_linked_table_id'), ['linked_table_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_path'), ['path'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_position'), ['position'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_project_id'), ['project_id'], unique=False)

    op.create_table('column_visibility',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('table_id', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.String(length=16), nullable=False),
    sa.Column('column_id', sa.String(length=16), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['column_id'], ['column_meta.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['table_meta.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id', 'user_id', 'column_id', name='_column_visibility_unique')
    )
    with op.batch_alter_table('column_visibility', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_column_visibility_table_id'), ['table_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_column_visibility_user_id'), ['user_id'], unique=False)

    op.create_table('field_meta',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('table_id', sa.String(length=16), nullable=True),
    sa.Column('column_id', sa.String(length=16), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['column_id'], ['column_meta.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['table_meta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filters',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('table_id', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.String(length=16), nullable=False),
    sa.Column('column_id', sa.String(length=16), nullable=False),
    sa.Column('operation', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('is_reusable', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['column_id'], ['column_meta.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['table_meta.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id', 'user_id', 'column_id', 'operation', 'value', name='_filter_unique')
    )
    with op.batch_alter_table('filters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_filters_table_id'), ['table_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_filters_user_id'), ['user_id'], unique=False)

    op.create_table('formulas',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('column_id', sa.String(length=16), nullable=True),
    sa.Column('formula', sa.Text(), nullable=False),
    sa.Column('formula_raw', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['column_id'], ['column_meta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lookup_columns',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('column_id', sa.String(length=16), nullable=False),
    sa.Column('relation_column_id', sa.String(length=16), nullable=False),
    sa.Column('lookup_column_id', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['column_id'], ['column_meta.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lookup_column_id'], ['column_meta.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relation_column_id'], ['column_meta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relation_meta',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('left_table_id', sa.String(), nullable=False),
    sa.Column('right_table_id', sa.String(), nullable=False),
    sa.Column('relation_type', sa.String(), nullable=False),
    sa.Column('fk_name', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('join_table_id', sa.String(), nullable=True),
    sa.Column('left_column_id', sa.String(length=16), nullable=True),
    sa.Column('right_column_id', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['join_table_id'], ['table_meta.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['left_column_id'], ['column_meta.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['left_table_id'], ['table_meta.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['right_column_id'], ['column_meta.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['right_table_id'], ['table_meta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('relation_meta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relation_meta_id'), ['id'], unique=False)

    op.create_table('rollups',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('column_id', sa.String(length=16), nullable=False),
    sa.Column('relation_column_id', sa.String(length=16), nullable=False),
    sa.Column('rollup_column_id', sa.String(length=16), nullable=True),
    sa.Column('aggregate_func', sa.String(), server_default=sa.text("'count'"), nullable=False),
    sa.Column('precision', sa.Integer(), nullable=True),
    sa.Column('show_thousands_sep', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['column_id'], ['column_meta.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relation_column_id'], ['column_meta.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rollup_column_id'], ['column_meta.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('column_id')
    )
    op.create_table('select_options',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('column_id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['column_id'], ['column_meta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sorts',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('table_id', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.String(length=16), nullable=False),
    sa.Column('column_id', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.String(), server_default=sa.text("'asc'"), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['column_id'], ['column_meta.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['table_meta.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id', 'user_id', 'column_id', name='_sort_unique')
    )
    with op.batch_alter_table('sorts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sorts_table_id'), ['table_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sorts_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sorts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sorts_user_id'))
        batch_op.drop_index(batch_op.f('ix_sorts_table_id'))

    op.drop_table('sorts')
    op.drop_table('select_options')
    op.drop_table('rollups')
    with op.batch_alter_table('relation_meta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relation_meta_id'))

    op.drop_table('relation_meta')
    op.drop_table('lookup_columns')
    op.drop_table('formulas')
    with op.batch_alter_table('filters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_filters_user_id'))
        batch_op.drop_index(batch_op.f('ix_filters_table_id'))

    op.drop_table('filters')
    op.drop_table('field_meta')
    with op.batch_alter_table('column_visibility', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_column_visibility_user_id'))
        batch_op.drop_index(batch_op.f('ix_column_visibility_table_id'))

    op.drop_table('column_visibility')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_project_id'))
        batch_op.drop_index(batch_op.f('ix_documents_position'))
        batch_op.drop_index(batch_op.f('ix_documents_path'))
        batch_op.drop_index(batch_op.f('ix_documents_parent_id'))
        batch_op.drop_index(batch_op.f('ix_documents_linked_table_id'))
        batch_op.drop_index(batch_op.f('ix_documents_linked_row_id'))
        batch_op.drop_index(batch_op.f('ix_documents_depth'))

    op.drop_table('documents')
    with op.batch_alter_table('dashboard_widgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dashboard_widgets_dashboard_id'))

    op.drop_table('dashboard_widgets')
    op.drop_table('column_meta')
    with op.batch_alter_table('table_meta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_table_meta_name'))

    op.drop_table('table_meta')
    op.drop_table('project_members')
    with op.batch_alter_table('process_recording_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_process_recording_files_session_id'))

    op.drop_table('process_recording_files')
    with op.batch_alter_table('dashboards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dashboards_user_id'))
        batch_op.drop_index(batch_op.f('ix_dashboards_project_id'))

    op.drop_table('dashboards')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_token_hash'))

    op.drop_table('sessions')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_name'))

    op.drop_table('projects')
    with op.batch_alter_table('process_recording_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_process_recording_sessions_user_id'))

    op.drop_table('process_recording_sessions')
    with op.batch_alter_table('auth_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_codes_user_id'))

    op.drop_table('auth_codes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_verification_tok'))
        batch_op.drop_index(batch_op.f('ix_users_reset_token'))
        batch_op.drop_index(batch_op.f('ix_users_normalized_email'))
        batch_op.drop_index(batch_op.f('ix_users_name'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('text_container')
    # ### end Alembic commands ###
