"""Add position to document

Revision ID: 3f09ef38c4c4
Revises: 31636a3debb1
Create Date: 2025-11-15 09:56:23.815094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f09ef38c4c4'
down_revision: Union[str, Sequence[str], None] = '31636a3debb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=True))

   

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
  

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###
