"""Seperate Table for Workflows

Revision ID: 53e4b109d12c
Revises: 6d29da951c79
Create Date: 2025-11-20 08:05:59.060513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53e4b109d12c'
down_revision: Union[str, Sequence[str], None] = '6d29da951c79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_recording_steps',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('session_id', sa.String(length=16), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('window_title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('global_position', sa.JSON(), nullable=True),
    sa.Column('relative_position', sa.JSON(), nullable=True),
    sa.Column('window_size', sa.JSON(), nullable=True),
    sa.Column('screenshot_size', sa.JSON(), nullable=True),
    sa.Column('screenshot_relative_position', sa.JSON(), nullable=True),
    sa.Column('key_pressed', sa.String(), nullable=True),
    sa.Column('text_typed', sa.Text(), nullable=True),
    sa.Column('scroll_delta', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['process_recording_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'step_number', name='_session_step_number_unique')
    )
    with op.batch_alter_table('process_recording_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_process_recording_steps_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('process_recording_sessions', schema=None) as batch_op:
        batch_op.drop_column('steps_metadata')

   

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('process_recording_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('steps_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))

    with op.batch_alter_table('process_recording_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_process_recording_steps_session_id'))

    op.drop_table('process_recording_steps')
    # ### end Alembic commands ###
