"""Documents Private Section

Revision ID: 6950da79b7de
Revises: 1c6f3375819c
Create Date: 2026-01-24 08:35:42.755082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6950da79b7de'
down_revision: Union[str, Sequence[str], None] = '1c6f3375819c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # FIX 1: Added server_default=sa.text('false') to documents
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_private', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('owner_id', sa.String(length=16), nullable=True))
        batch_op.create_index(batch_op.f('ix_documents_is_private'), ['is_private'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_owner_id'), ['owner_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'], ondelete='CASCADE')

    # FIX 2: Added server_default=sa.text('false') to folders
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_private', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('owner_id', sa.String(length=16), nullable=True))
        batch_op.create_index(batch_op.f('ix_folders_is_private'), ['is_private'], unique=False)
        batch_op.create_index(batch_op.f('ix_folders_owner_id'), ['owner_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'], ondelete='CASCADE')

    # FIX 3: Added server_default=sa.text('false') to process_recording_sessions
    with op.batch_alter_table('process_recording_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_private', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('owner_id', sa.String(length=16), nullable=True))
        batch_op.create_index(batch_op.f('ix_process_recording_sessions_is_private'), ['is_private'], unique=False)
        batch_op.create_index(batch_op.f('ix_process_recording_sessions_owner_id'), ['owner_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'], ondelete='CASCADE')



    # ### end Alembic commands ###

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
  

    with op.batch_alter_table('process_recording_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_process_recording_sessions_owner_id'))
        batch_op.drop_index(batch_op.f('ix_process_recording_sessions_is_private'))
        batch_op.drop_column('owner_id')
        batch_op.drop_column('is_private')

    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_folders_owner_id'))
        batch_op.drop_index(batch_op.f('ix_folders_is_private'))
        batch_op.drop_column('owner_id')
        batch_op.drop_column('is_private')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_documents_owner_id'))
        batch_op.drop_index(batch_op.f('ix_documents_is_private'))
        batch_op.drop_column('owner_id')
        batch_op.drop_column('is_private')

    # ### end Alembic commands ###
