"""Adding Project and folder to workflow

Revision ID: 6d29da951c79
Revises: 3f09ef38c4c4
Create Date: 2025-11-19 09:09:24.766814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d29da951c79'
down_revision: Union[str, Sequence[str], None] = '3f09ef38c4c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('position',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_documents_position'), ['position'], unique=False)

    with op.batch_alter_table('process_recording_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('project_id', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('folder_id', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_expanded', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_process_recording_sessions_folder_id'), ['folder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_process_recording_sessions_position'), ['position'], unique=False)
        batch_op.create_index(batch_op.f('ix_process_recording_sessions_project_id'), ['project_id'], unique=False)
        batch_op.create_foreign_key(None, 'folders', ['folder_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='CASCADE')

   

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
 

    with op.batch_alter_table('process_recording_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_process_recording_sessions_project_id'))
        batch_op.drop_index(batch_op.f('ix_process_recording_sessions_position'))
        batch_op.drop_index(batch_op.f('ix_process_recording_sessions_folder_id'))
        batch_op.drop_column('is_expanded')
        batch_op.drop_column('position')
        batch_op.drop_column('folder_id')
        batch_op.drop_column('project_id')
        batch_op.drop_column('name')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_position'))
        batch_op.alter_column('position',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
