"""Adding Steps type

Revision ID: bc8520130736
Revises: 53e4b109d12c
Create Date: 2025-11-20 08:21:00.063229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc8520130736'
down_revision: Union[str, Sequence[str], None] = '53e4b109d12c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process_recording_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('step_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))
        batch_op.alter_column('action_type',
               existing_type=sa.VARCHAR(),
               nullable=True)

  

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('process_recording_steps', schema=None) as batch_op:
        batch_op.alter_column('action_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('content')
        batch_op.drop_column('step_type')

    # ### end Alembic commands ###
