"""Browser management using Playwright — with browser-use-level stealth."""

import asyncio
import logging
import os
import zipfile
import httpx
from contextlib import asynccontextmanager
from pathlib import Path
from typing import AsyncGenerator, Optional
from playwright.async_api import async_playwright, Browser, BrowserContext, Page

logger = logging.getLogger(__name__)

# ── Chrome flags copied from browser-use/browser/profile.py ──────
# These suppress automation indicators and optimize for agent use.

STEALTH_ARGS = [
    '--no-default-browser-check',
    '--disable-blink-features=AutomationControlled',
    '--disable-infobars',
    '--disable-background-timer-throttling',
    '--disable-backgrounding-occluded-windows',
    '--disable-renderer-backgrounding',
    '--no-first-run',
    '--no-pings',
    '--disable-sync',
    '--disable-default-apps',
    '--disable-domain-reliability',
    '--disable-external-intent-requests',
    '--disable-desktop-notifications',
    '--noerrdialogs',
    '--disable-speech-synthesis-api',
    '--disable-speech-api',
    '--disable-print-preview',
    '--safebrowsing-disable-auto-update',
    '--hide-crash-restore-bubble',
    '--suppress-message-center-popups',
    '--simulate-outdated-no-au=Tue, 31 Dec 2099 23:59:59 GMT',
    '--ash-no-nudges',
    '--log-level=2',
    '--allow-pre-commit-input',
    '--generate-pdf-document-outline',
    '--install-autogenerated-theme=0,0,0',
    '--disable-features=AcceptCHFrame,AutoExpandDetailsElement,AvoidUnnecessaryBeforeUnloadCheckSync,CertificateTransparencyComponentUpdater,DeferRendererTasksAfterInput,DestroyProfileOnBrowserClose,DialMediaRouteProvider,GlobalMediaControls,HttpsUpgrades,ImprovedCookieControls,LazyFrameLoading,LensOverlay,MediaRouter,PaintHolding,ThirdPartyStoragePartitioning,Translate',
]

# Args to IGNORE from Playwright's defaults (browser-use pattern)
IGNORE_DEFAULT_ARGS = [
    '--enable-automation',
    '--disable-extensions',
    '--hide-scrollbars',
]

# Stealth JavaScript injected into every page
STEALTH_JS = """
// Remove webdriver indicator
Object.defineProperty(navigator, 'webdriver', { get: () => undefined });
delete navigator.__proto__.webdriver;

// Add chrome runtime (missing in headless)
if (!window.chrome) {
    window.chrome = {};
}
if (!window.chrome.runtime) {
    window.chrome.runtime = {
        connect: function() { return { onMessage: { addListener: function() {} } }; },
        sendMessage: function() {},
    };
}

// Fix permissions API
const originalQuery = window.navigator.permissions.query;
window.navigator.permissions.query = (parameters) =>
    parameters.name === 'notifications'
        ? Promise.resolve({ state: Notification.permission })
        : originalQuery(parameters);

// Fix plugins (headless has 0 plugins)
Object.defineProperty(navigator, 'plugins', {
    get: () => [
        { name: 'Chrome PDF Plugin', filename: 'internal-pdf-viewer' },
        { name: 'Chrome PDF Viewer', filename: 'mhjfbmdgcfjbbpaeojofohoefgiehjai' },
        { name: 'Native Client', filename: 'internal-nacl-plugin' },
    ],
});

// Fix languages
Object.defineProperty(navigator, 'languages', {
    get: () => ['en-US', 'en'],
});

// Fix platform (sometimes missing in headless)
if (!navigator.platform) {
    Object.defineProperty(navigator, 'platform', {
        get: () => 'MacIntel',
    });
}

// Prevent iframe detection of automation
try {
    Object.defineProperty(HTMLIFrameElement.prototype, 'contentWindow', {
        get: function() {
            return window;
        }
    });
} catch (e) {}

// Fix WebGL vendor/renderer (headless gives "Google Inc." which is detectable)
const getParameter = WebGLRenderingContext.prototype.getParameter;
WebGLRenderingContext.prototype.getParameter = function(parameter) {
    if (parameter === 37445) return 'Intel Inc.';
    if (parameter === 37446) return 'Intel Iris OpenGL Engine';
    return getParameter.call(this, parameter);
};
"""

# Realistic user agents by platform
USER_AGENTS = {
    'macos': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36',
    'windows': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36',
    'linux': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36',
}

# ── Extension Management (browser-use pattern) ───────────────────

EXTENSIONS = [
    {
        'name': "I still don't care about cookies",
        'id': 'edibdbjcniadpccecjdfdjjppcpchdlm',
        'url': 'https://clients2.google.com/service/update2/crx?response=redirect&prodversion=133&acceptformat=crx3&x=id%3Dedibdbjcniadpccecjdfdjjppcpchdlm%26uc',
    },
]


async def _ensure_extensions(cache_dir: Path) -> list[str]:
    """Download and cache extensions, return list of paths."""
    cache_dir.mkdir(parents=True, exist_ok=True)
    paths = []
    
    async with httpx.AsyncClient(follow_redirects=True, timeout=30.0) as client:
        for ext in EXTENSIONS:
            ext_dir = cache_dir / ext['id']
            if ext_dir.exists() and any(ext_dir.iterdir()):
                paths.append(str(ext_dir))
                continue
            
            try:
                logger.info(f"Downloading extension: {ext['name']}...")
                resp = await client.get(ext['url'])
                if resp.status_code != 200:
                    logger.warning(f"Failed to download {ext['name']}: {resp.status_code}")
                    continue
                
                crx_path = cache_dir / f"{ext['id']}.crx"
                crx_path.write_bytes(resp.content)
                
                # CRX files are ZIP with a header — extract after skipping header
                ext_dir.mkdir(parents=True, exist_ok=True)
                try:
                    with zipfile.ZipFile(crx_path, 'r') as z:
                        z.extractall(ext_dir)
                except zipfile.BadZipFile:
                    # CRX v3: skip first ~16 bytes + header
                    data = resp.content
                    # Find PK signature
                    pk_offset = data.find(b'PK\x03\x04')
                    if pk_offset > 0:
                        import io
                        with zipfile.ZipFile(io.BytesIO(data[pk_offset:]), 'r') as z:
                            z.extractall(ext_dir)
                    else:
                        logger.warning(f"Could not extract {ext['name']}")
                        continue
                
                crx_path.unlink(missing_ok=True)
                paths.append(str(ext_dir))
                logger.info(f"Installed extension: {ext['name']}")
                
            except Exception as e:
                logger.warning(f"Extension {ext['name']} failed: {e}")
    
    return paths


# ── Browser Manager ──────────────────────────────────────────────

class BrowserManager:
    """Manages Playwright browser lifecycle with browser-use-level stealth."""
    
    def __init__(
        self,
        headless: bool = True,
        browser_type: str = "chromium",
        viewport_size: tuple[int, int] = (1280, 720),
        user_data_dir: Optional[str] = None,
        proxy: Optional[str] = None,
        use_extensions: bool = True,
        stealth: bool = True,
    ):
        self.headless = headless
        self.browser_type = browser_type
        self.viewport_size = viewport_size
        self.user_data_dir = user_data_dir
        self.proxy = proxy
        self.use_extensions = use_extensions and not headless  # Extensions only work headed
        self.stealth = stealth
        self._browser: Optional[Browser] = None
        self._context: Optional[BrowserContext] = None
        self._playwright = None
    
    async def launch(self) -> Browser:
        """Launch browser instance with stealth configuration."""
        if self._browser:
            return self._browser
        
        self._playwright = await async_playwright().start()
        
        if self.browser_type == "chromium":
            browser_launcher = self._playwright.chromium
        elif self.browser_type == "firefox":
            browser_launcher = self._playwright.firefox
        else:
            browser_launcher = self._playwright.webkit
        
        args = list(STEALTH_ARGS) if self.stealth else []
        ignore_defaults = list(IGNORE_DEFAULT_ARGS) if self.stealth else []
        
        # Load extensions if requested (headed mode only)
        if self.use_extensions:
            ext_cache = Path.home() / '.stept' / 'extensions'
            ext_paths = await _ensure_extensions(ext_cache)
            if ext_paths:
                args.append(f'--disable-extensions-except={",".join(ext_paths)}')
                args.append(f'--load-extension={",".join(ext_paths)}')
        
        launch_options = {
            "headless": self.headless,
            "args": args,
            "ignore_default_args": ignore_defaults,
        }
        
        if self.proxy:
            launch_options["proxy"] = {"server": self.proxy}
        
        self._browser = await browser_launcher.launch(**launch_options)
        logger.info(f"Browser launched: {self.browser_type}, headless={self.headless}, stealth={self.stealth}")
        return self._browser
    
    async def new_context(self, **kwargs) -> BrowserContext:
        """Create new browser context with stealth settings."""
        browser = await self.launch()
        
        import platform
        os_name = platform.system().lower()
        if 'darwin' in os_name:
            ua = USER_AGENTS['macos']
        elif 'windows' in os_name:
            ua = USER_AGENTS['windows']
        else:
            ua = USER_AGENTS['linux']
        
        context_options = {
            "viewport": {"width": self.viewport_size[0], "height": self.viewport_size[1]},
            "user_agent": ua,
            "locale": "en-US",
            "timezone_id": "America/New_York",
            "permissions": ["geolocation"],
            "color_scheme": "light",
            "accept_downloads": True,
        }
        context_options.update(kwargs)
        
        self._context = await browser.new_context(**context_options)
        
        # Inject stealth scripts
        if self.stealth:
            await self._context.add_init_script(STEALTH_JS)
        
        # Auto-dismiss dialogs
        self._context.on("dialog", self._handle_dialog)
        self._context.on("page", self._handle_new_page)
        
        logger.info("Browser context created with stealth settings")
        return self._context
    
    async def new_page(self, **context_kwargs) -> Page:
        """Create new page in new context."""
        context = await self.new_context(**context_kwargs)
        page = await context.new_page()
        page.on("pageerror", lambda err: logger.error(f"Page error: {err}"))
        return page
    
    async def close(self):
        """Close browser and cleanup."""
        if self._context:
            try:
                await self._context.close()
            except Exception:
                pass
            self._context = None
        
        if self._browser:
            try:
                await self._browser.close()
            except Exception:
                pass
            self._browser = None
        
        if self._playwright:
            try:
                await self._playwright.stop()
            except Exception:
                pass
            self._playwright = None
        
        logger.info("Browser closed")
    
    def _handle_dialog(self, dialog):
        """Auto-dismiss dialogs."""
        logger.info(f"Auto-dismissing dialog: {dialog.type} - {dialog.message}")
        asyncio.create_task(dialog.accept())
    
    def _handle_new_page(self, page):
        """Handle new page/tab events."""
        logger.info(f"New page opened: {page.url}")
    
    @asynccontextmanager
    async def page_context(self, **kwargs) -> AsyncGenerator[Page, None]:
        """Context manager for page lifecycle."""
        page = None
        try:
            page = await self.new_page(**kwargs)
            yield page
        finally:
            if page:
                try:
                    await page.close()
                except Exception:
                    pass
            await self.close()
    
    async def __aenter__(self):
        return await self.launch()
    
    async def __aexit__(self, exc_type, exc_val, exc_tb):
        await self.close()


@asynccontextmanager
async def browser_page(headless: bool = True, **kwargs) -> AsyncGenerator[Page, None]:
    """Quick context manager for a browser page."""
    manager = BrowserManager(headless=headless)
    async with manager.page_context(**kwargs) as page:
        yield page
